# Generated by Django 2.2 on 2019-04-03 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Subcounty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.District')),
            ],
        ),
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sub_county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.Subcounty')),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Telephone', models.CharField(max_length=30)),
                ('parish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.Subcounty')),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marriage_status', models.CharField(choices=[('Married', 'Married'), ('Single', 'Single')], max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(default='./static/images/no_img.jpg', upload_to='../Media/')),
                ('Gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'male')], max_length=20)),
                ('officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='officer', to='Users.Officer')),
            ],
        ),
    ]
