# Generated by Django 2.2 on 2019-04-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='login_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='password',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
